Import Upstream version 3.6.2

diff --git a/prog/pwm/fancontrol b/prog/pwm/fancontrol
--- a/prog/pwm/fancontrol
+++ b/prog/pwm/fancontrol
@@ -38,7 +38,7 @@
 #
 #
 
-PIDFILE="/var/run/fancontrol.pid"
+PIDFILE="/run/fancontrol.pid"
 
 #DEBUG=1
 MAX=255
@@ -118,30 +118,79 @@ function LoadConfig
 			echo "MINTEMP must be less than MAXTEMP" >&2
 			exit 1
 		fi
-		if [ "${AFCMAXPWM[$fcvcount]}" -gt 255 ]
-		then
-			echo "Error in configuration file (${AFCPWM[$fcvcount]}):" >&2
-			echo "MAXPWM must be at most 255" >&2
-			exit 1
-		fi
-		if [ "${AFCMINSTOP[$fcvcount]}" -ge "${AFCMAXPWM[$fcvcount]}" ]
-		then
-			echo "Error in configuration file (${AFCPWM[$fcvcount]}):" >&2
-			echo "MINSTOP must be less than MAXPWM" >&2
-			exit 1
-		fi
-		if [ "${AFCMINSTOP[$fcvcount]}" -lt "${AFCMINPWM[$fcvcount]}" ]
-		then
-			echo "Error in configuration file (${AFCPWM[$fcvcount]}):" >&2
-			echo "MINSTOP must be greater than or equal to MINPWM" >&2
-			exit 1
-		fi
-		if [ "${AFCMINPWM[$fcvcount]}" -lt 0 ]
-		then
-			echo "Error in configuration file (${AFCPWM[$fcvcount]}):" >&2
-			echo "MINPWM must be at least 0" >&2
-			exit 1
-		fi
+
+        if [ "${AFCMINPWM[$fvcount]}" -lt "${AFCMAXPWM[$fvcount]}" ]; then
+           # Normal drive:
+           # PWM value 0   -> Fan not spinning
+           # PWM value 255 -> Fan spinning at full speed
+
+		   if [ "${AFCMAXPWM[$fcvcount]}" -gt $MAX ]
+		   then
+			   echo "Error in configuration file (${AFCPWM[$fcvcount]}):" >&2
+			   echo "For normal drive MAXPWM must be at most $MAX" >&2
+		       exit 1
+		   fi
+
+		   if [ "${AFCMINSTOP[$fcvcount]}" -ge "${AFCMAXPWM[$fcvcount]}" ]
+		   then
+			   echo "Error in configuration file (${AFCPWM[$fcvcount]}):" >&2
+			   echo "For normal drive MINSTOP must be less than MAXPWM" >&2
+			   exit 1
+		   fi
+
+		   if [ "${AFCMINSTOP[$fcvcount]}" -lt "${AFCMINPWM[$fcvcount]}" ]
+		   then
+			   echo "Error in configuration file (${AFCPWM[$fcvcount]}):" >&2
+			   echo "For normal drive MINSTOP must be greater than or equal to MINPWM" >&2
+			   exit 1
+		   fi
+
+		   if [ "${AFCMINPWM[$fcvcount]}" -lt 0 ]
+		   then
+			   echo "Error in configuration file (${AFCPWM[$fcvcount]}):" >&2
+			   echo "For normal drive MINPWM must be at least 0" >&2
+			   exit 1
+		   fi
+
+        elif [ "${AFCMINPWM[$fvcount]}" -gt "${AFCMAXPWM[$fvcount]}" ]; then
+            # Inverted drive:
+            # PWM value 255   -> Fan not spinning
+            # PWM value 0 -> Fan spinning at full speed
+
+		    if [ "${AFCMINPWM[$fcvcount]}" -gt $MAX ]
+		    then
+			    echo "Error in configuration file (${AFCPWM[$fcvcount]}):" >&2
+			    echo "For inverted drive MINPWM must be at most $MAX" >&2
+		        exit 1
+		    fi
+
+		    if [ "${AFCMINSTOP[$fcvcount]}" -lt "${AFCMAXPWM[$fcvcount]}" ]
+		    then
+			    echo "Error in configuration file (${AFCPWM[$fcvcount]}):" >&2
+			    echo "For inverted drive MINSTOP must be larger than MAXPWM" >&2
+			    exit 1
+		    fi
+
+		    if [ "${AFCMINSTOP[$fcvcount]}" -ge "${AFCMINPWM[$fcvcount]}" ]
+		    then
+			    echo "Error in configuration file (${AFCPWM[$fcvcount]}):" >&2
+			    echo "For inverted drive MINSTOP must be less than MINPWM" >&2
+			    exit 1
+		    fi
+
+		    if [ "${AFCMAXPWM[$fcvcount]}" -lt 0 ]
+		    then
+			    echo "Error in configuration file (${AFCPWM[$fcvcount]}):" >&2
+			    echo "For inverted drive MAXPWM must be at least 0" >&2
+			    exit 1
+		    fi
+
+        else
+            echo "Error in configuration file (${AFCPWM[$fcvcount]}):" >&2
+            echo "MINPWM and MAXPWM cannot be equal" >&2
+            exit 1
+        fi
+
 		if [ "${AFCAVERAGE[$fcvcount]}" -lt 1 ]
 		then
 			echo "Error in configuration file (${AFCPWM[$fcvcount]}):" >&2
@@ -287,7 +336,7 @@ function CheckFiles
 		pwmo=${AFCPWM[$fcvcount]}
 		if [ ! -w $pwmo ]
 		then
-			echo "Error: file $pwmo doesn't exist" >&2
+			echo "Error: file $pwmo doesn't exist or isn't writable" >&2
 			outdated=1
 		fi
 		let fcvcount=$fcvcount+1
@@ -297,10 +346,19 @@ function CheckFiles
 	while (( $fcvcount < ${#AFCTEMP[@]} )) # go through all temp inputs
 	do
 		tsen=${AFCTEMP[$fcvcount]}
-		if [ ! -r $tsen ]
+		if [ ${tsen::1} == "!" ]
 		then
-			echo "Error: file $tsen doesn't exist" >&2
-			outdated=1
+			if ! [ -x ${tsen:1} ]
+			then
+				echo "Error: file ${tsen:1} doesn't exist or isn't executable" >&2
+				outdated=1
+			fi
+		else
+			if ! [ -r $tsen ]
+			then
+				echo "Error: file $tsen doesn't exist or isn't readable" >&2
+				outdated=1
+			fi
 		fi
 		let fcvcount=$fcvcount+1
 	done
@@ -313,7 +371,7 @@ function CheckFiles
 		do
 			if [ ! -r $fan ]
 			then
-				echo "Error: file $fan doesn't exist" >&2
+				echo "Error: file $fan doesn't exist or isn't readable" >&2
 				outdated=1
 			fi
 		done
@@ -323,7 +381,8 @@ function CheckFiles
 	if [ $outdated -eq 1 ]
 	then
 		echo >&2
-		echo "At least one referenced file is missing. Either some required kernel" >&2
+		echo "At least one referenced file is missing or doesn't have" >&2
+		echo "correct privileges. Either some required kernel" >&2
 		echo "modules haven't been loaded, or your configuration file is outdated." >&2
 		echo "In the latter case, you should run pwmconfig again." >&2
 	fi
@@ -489,7 +548,7 @@ function pwmenable()
 		fi
 		# enable manual control by fancontrol
 		echo 1 > $ENABLE 2> /dev/null
-		if [ $? -ne 0 ]
+		if [ "$(cat $ENABLE)" -ne 1 ]
 		then
 			return 1
 		fi
@@ -540,7 +599,12 @@ function UpdateFanSpeeds
 		maxpwm=${AFCMAXPWM[$fcvcount]}
 		avg=${AFCAVERAGE[$fcvcount]}
 
-		read tlastval < ${tsens}
+		if [ ${tsens::1} == "!" ]
+		then
+			tlastval="$(${tsens:1})"
+		else
+			read tlastval < ${tsens}
+		fi
 		if [ $? -ne 0 ]
 		then
 			echo "Error reading temperature from $DIR/$tsens"
